name: Windows

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Schedule the workflow to run every 5 hours
  schedule:
    - cron: "0 */5 * * *"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Config
        run: New-LocalUser -Name "Golden" -Password (ConvertTo-SecureString "Jurtg@(3456" -AsPlainText -Force) -FullName "Golden Chalk" -Description "...."
             Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
             choco install ngrok
             ngrok config add-authtoken 2dEyxB5ml6BSMTSE2IFuVfH5XAm_5jeqegdgEtwXWVuygVKKx
             ngrok tcp 3389

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
